# Pricing engine calibration

Anton Antonov  
August 2026

---

## Introduction

This notebook shows how to calibration a Geo-pricing-engine model using specifications from a JSON file.

---

## Setup

In [17]:
from GeoSpatialPricingEngine import *
import random
import os

In [10]:
%load_ext JupyterChatbook

The JupyterChatbook extension is already loaded. To reload it, use:
  %reload_ext JupyterChatbook

---

## Build with default setup

Invoke the pricing engine builder with [default spec](../../resources/PricingEngineCalibrationSpec.json):

In [12]:
pebObj=PricingEngineBuilder.build_from_json(file_path=os.path.abspath("./TestSpec.json"))

pebObj

Builder's Geo-taxonomy:

In [13]:
pebObj.geo_taxonomy.data

,id,geo_taxonomy_id,tile_id,center_lat,center_lon,coordinates
0,1,Hextile1deg,tile00001,42.435245,-124.5,"[[-125.0, 42.7239199200323], [-125.0, 42.14656..."
1,2,Hextile1deg,tile00002,47.631397,-124.5,"[[-125.0, 47.92007234273893], [-125.0, 47.3427..."
2,3,Hextile1deg,tile00003,39.837169,-124.0,"[[-124.5, 40.125843708678985], [-124.5, 39.548..."
3,4,Hextile1deg,tile00004,41.569219,-124.0,"[[-124.5, 41.85789451624787], [-124.5, 41.2805..."
4,5,Hextile1deg,tile00005,43.301270,-124.0,"[[-124.5, 43.58994532381674], [-124.5, 43.0125..."
...,...,...,...,...,...,...
1038,1039,Hextile1deg,tile01039,45.899346,-68.5,"[[-69.0, 46.18802153517006], [-69.0, 45.610671..."
1039,1040,Hextile1deg,tile01040,45.033321,-68.0,"[[-68.5, 45.32199613138562], [-68.5, 44.744645..."
1040,1041,Hextile1deg,tile01041,46.765372,-68.0,"[[-68.5, 47.05404693895449], [-68.5, 46.476696..."
1041,1042,Hextile1deg,tile01042,45.899346,-67.5,"[[-68.0, 46.18802153517006], [-68.0, 45.610671..."
1042,1043,Hextile1deg,tile01043,45.033321,-67.0,"[[-67.5, 45.32199613138562], [-67.5, 44.744645..."

Builder's transportation orders:

In [14]:
pebObj.orders.data

,id,transportation_trips_id,raw_transportation_trips_id,start_lat,start_lon,end_lat,end_lon,distance,price,is_training
0,2,FAFDerivedLinear,FAFDerived,42.665745,-73.798353,33.762909,-84.422674,1004.7467,250.9493,True
1,3,FAFDerivedLinear,FAFDerived,42.665745,-73.798353,30.300536,-97.755044,1835.9657,417.1931,True
2,4,FAFDerivedLinear,FAFDerived,42.665745,-73.798353,39.300213,-76.610516,325.9673,115.1935,True
3,5,FAFDerivedLinear,FAFDerived,42.665745,-73.798353,30.448453,-91.125899,1481.5256,346.3051,True
4,6,FAFDerivedLinear,FAFDerived,42.665745,-73.798353,30.084343,-94.145774,1667.8959,383.5792,True
...,...,...,...,...,...,...,...,...,...,...
4551,4553,FAFDerivedLinear,FAFDerived,37.689363,-97.343805,27.967534,-82.475404,1362.1461,322.4292,True
4552,4554,FAFDerivedLinear,FAFDerived,37.689363,-97.343805,32.154289,-110.871062,1143.3852,278.6770,True
4553,4555,FAFDerivedLinear,FAFDerived,37.689363,-97.343805,36.127949,-95.902316,183.7673,86.7535,True
4554,4556,FAFDerivedLinear,FAFDerived,37.689363,-97.343805,36.779322,-76.024020,1367.7920,323.5584,True
4555,4557,FAFDerivedLinear,FAFDerived,37.689363,-97.343805,38.904148,-77.017094,1261.7769,302.3554,True

Tiled region object:

In [15]:
pebObj.tiled_region

Number of derived calibration records:

In [19]:
len(pebObj.calibration_records)

4556

Sample of records:

In [20]:
random.sample(list(pebObj.calibration_records.items()), 4)

[('228',
  {'id': '228',
   'path': ['tile00984', 'tile01014'],
   'distance': 300.4224,
   'price': 110.0845}),
 ('1240',
  {'id': '1240',
   'path': ['tile00875', 'tile00156'],
   'distance': 2012.4484,
   'price': 452.4897}),
 ('3541',
  {'id': '3541',
   'path': ['tile00972', 'tile00514'],
   'distance': 1522.6094,
   'price': 354.5219}),
 ('1366',
  {'id': '1366',
   'path': ['tile00845', 'tile00903'],
   'distance': 600.3624,
   'price': 170.0725})]